packages:
  - packages/*
  - examples/*
  - examples/*/*

gitChecks: false

linkWorkspacePackages: true

onlyBuiltDependencies:
  - nx

preferWorkspacePackages: true

storeDir: ./node_modules/.pnpm-store
