import type { EditorThemeClasses } from 'lexical';

const theme: EditorThemeClasses = {
	autocomplete: 'InkBlocksTheme__autocomplete',
	blockCursor: 'InkBlocksTheme__blockCursor',
	characterLimit: 'InkBlocksTheme__characterLimit',
	code: 'InkBlocksTheme__code',
	codeHighlight: {
		atrule: 'InkBlocksTheme__tokenAttr',
		attr: 'InkBlocksTheme__tokenAttr',
		boolean: 'InkBlocksTheme__tokenProperty',
		builtin: 'InkBlocksTheme__tokenSelector',
		cdata: 'InkBlocksTheme__tokenComment',
		char: 'InkBlocksTheme__tokenSelector',
		class: 'InkBlocksTheme__tokenFunction',
		'class-name': 'InkBlocksTheme__tokenFunction',
		comment: 'InkBlocksTheme__tokenComment',
		constant: 'InkBlocksTheme__tokenProperty',
		deleted: 'InkBlocksTheme__tokenDeleted',
		doctype: 'InkBlocksTheme__tokenComment',
		entity: 'InkBlocksTheme__tokenOperator',
		function: 'InkBlocksTheme__tokenFunction',
		important: 'InkBlocksTheme__tokenVariable',
		inserted: 'InkBlocksTheme__tokenInserted',
		keyword: 'InkBlocksTheme__tokenAttr',
		namespace: 'InkBlocksTheme__tokenVariable',
		number: 'InkBlocksTheme__tokenProperty',
		operator: 'InkBlocksTheme__tokenOperator',
		prolog: 'InkBlocksTheme__tokenComment',
		property: 'InkBlocksTheme__tokenProperty',
		punctuation: 'InkBlocksTheme__tokenPunctuation',
		regex: 'InkBlocksTheme__tokenVariable',
		selector: 'InkBlocksTheme__tokenSelector',
		string: 'InkBlocksTheme__tokenSelector',
		symbol: 'InkBlocksTheme__tokenProperty',
		tag: 'InkBlocksTheme__tokenProperty',
		unchanged: 'InkBlocksTheme__tokenUnchanged',
		url: 'InkBlocksTheme__tokenOperator',
		variable: 'InkBlocksTheme__tokenVariable',
	},
	embedBlock: {
		base: 'InkBlocksTheme__embedBlock',
		focus: 'InkBlocksTheme__embedBlockFocus',
	},
	hashtag: 'InkBlocksTheme__hashtag',
	heading: {
		h1: 'InkBlocksTheme__h1',
		h2: 'InkBlocksTheme__h2',
		h3: 'InkBlocksTheme__h3',
		h4: 'InkBlocksTheme__h4',
		h5: 'InkBlocksTheme__h5',
		h6: 'InkBlocksTheme__h6',
	},
	hr: 'InkBlocksTheme__hr',
	hrSelected: 'InkBlocksTheme__hrSelected',
	image: 'editor-image',
	indent: 'InkBlocksTheme__indent',
	layoutContainer: 'InkBlocksTheme__layoutContainer',
	layoutItem: 'InkBlocksTheme__layoutItem',
	link: 'InkBlocksTheme__link',
	list: {
		checklist: 'InkBlocksTheme__checklist',
		listitem: 'InkBlocksTheme__listItem',
		listitemChecked: 'InkBlocksTheme__listItemChecked',
		listitemUnchecked: 'InkBlocksTheme__listItemUnchecked',
		nested: {
			listitem: 'InkBlocksTheme__nestedListItem',
		},
		olDepth: [
			'InkBlocksTheme__ol1',
			'InkBlocksTheme__ol2',
			'InkBlocksTheme__ol3',
			'InkBlocksTheme__ol4',
			'InkBlocksTheme__ol5',
		],
		ul: 'InkBlocksTheme__ul',
	},
	mark: 'InkBlocksTheme__mark',
	markOverlap: 'InkBlocksTheme__markOverlap',
	paragraph: 'InkBlocksTheme__paragraph',
	quote: 'InkBlocksTheme__quote',
	specialText: 'InkBlocksTheme__specialText',
	tab: 'InkBlocksTheme__tabNode',
	table: 'InkBlocksTheme__table',
	tableAddColumns: 'InkBlocksTheme__tableAddColumns',
	tableAddRows: 'InkBlocksTheme__tableAddRows',
	tableAlignment: {
		center: 'InkBlocksTheme__tableAlignmentCenter',
		right: 'InkBlocksTheme__tableAlignmentRight',
	},
	tableCell: 'InkBlocksTheme__tableCell',
	tableCellActionButton: 'InkBlocksTheme__tableCellActionButton',
	tableCellActionButtonContainer:
		'InkBlocksTheme__tableCellActionButtonContainer',
	tableCellHeader: 'InkBlocksTheme__tableCellHeader',
	tableCellResizer: 'InkBlocksTheme__tableCellResizer',
	tableCellSelected: 'InkBlocksTheme__tableCellSelected',
	tableFrozenColumn: 'InkBlocksTheme__tableFrozenColumn',
	tableFrozenRow: 'InkBlocksTheme__tableFrozenRow',
	tableRowStriping: 'InkBlocksTheme__tableRowStriping',
	tableScrollableWrapper: 'InkBlocksTheme__tableScrollableWrapper',
	tableSelected: 'InkBlocksTheme__tableSelected',
	tableSelection: 'InkBlocksTheme__tableSelection',
	text: {
		bold: 'InkBlocksTheme__textBold',
		capitalize: 'InkBlocksTheme__textCapitalize',
		code: 'InkBlocksTheme__textCode',
		highlight: 'InkBlocksTheme__textHighlight',
		italic: 'InkBlocksTheme__textItalic',
		lowercase: 'InkBlocksTheme__textLowercase',
		strikethrough: 'InkBlocksTheme__textStrikethrough',
		subscript: 'InkBlocksTheme__textSubscript',
		superscript: 'InkBlocksTheme__textSuperscript',
		underline: 'InkBlocksTheme__textUnderline',
		underlineStrikethrough: 'InkBlocksTheme__textUnderlineStrikethrough',
		uppercase: 'InkBlocksTheme__textUppercase',
	},
};

export default theme;
